### ISSUE TITLE
support node modules

### ISSUE THREAD

**Issue by twlite** [customrealms/core#29]
Hi, it would be great to have node modules support. Being able to use some useful libs with this enhances the development experience even more.

**Comment by twlite** [comment]
I guess it is a possible duplicate of https://github.com/customrealms/bukkit-runtime/issues/1

closing this

**Comment by FalcoG** [comment]
It's already possible to use certain node modules, for example "mysql" from npm works fine after configuring webpack. 

Out of the box webpack is targeted at web rather than node. Modify your ``webpack.config.js`` and set ``target: 'node'``. In addition for some packages to work (such as mysql, see: https://github.com/mysqljs/mysql/issues/1655), you have to disable webpack's minimization.

This is done by adding the following to ``webpack.config.js``: 
``optimization: { minimize: false }``

Note: Beware that bukkit-runtime ships with quite an old node version, so not all packages will be compatible.
